"""Add all tables

Revision ID: 508927af516d
Revises:
Create Date: 2026-01-13 14:30:40.255860+08:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '508927af516d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('celery_taskmeta',
    sa.Column('create_time', sa.DateTime(), nullable=False, comment='Create time'),
    sa.Column('update_time', sa.DateTime(), nullable=False, comment='Update time'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('task_id', sqlmodel.sql.sqltypes.AutoString(length=155), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('result', sa.PickleType(), nullable=True),
    sa.Column('date_done', sa.DateTime(timezone=True), nullable=True),
    sa.Column('traceback', sa.Text(), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=155), nullable=True),
    sa.Column('args', sa.LargeBinary(), nullable=True),
    sa.Column('kwargs', sa.LargeBinary(), nullable=True),
    sa.Column('worker', sqlmodel.sql.sqltypes.AutoString(length=155), nullable=True),
    sa.Column('retries', sa.Integer(), nullable=True),
    sa.Column('queue', sqlmodel.sql.sqltypes.AutoString(length=155), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('task_id')
    )
    op.create_index(op.f('ix_celery_taskmeta_create_time'), 'celery_taskmeta', ['create_time'], unique=False)
    op.create_index(op.f('ix_celery_taskmeta_update_time'), 'celery_taskmeta', ['update_time'], unique=False)
    op.create_table('celery_tasksetmeta',
    sa.Column('create_time', sa.DateTime(), nullable=False, comment='Create time'),
    sa.Column('update_time', sa.DateTime(), nullable=False, comment='Update time'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('taskset_id', sqlmodel.sql.sqltypes.AutoString(length=155), nullable=False),
    sa.Column('result', sa.PickleType(), nullable=True),
    sa.Column('date_done', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('taskset_id')
    )
    op.create_index(op.f('ix_celery_tasksetmeta_create_time'), 'celery_tasksetmeta', ['create_time'], unique=False)
    op.create_index(op.f('ix_celery_tasksetmeta_update_time'), 'celery_tasksetmeta', ['update_time'], unique=False)
    op.create_table('image_assets',
    sa.Column('create_time', sa.DateTime(), nullable=False, comment='Create time'),
    sa.Column('update_time', sa.DateTime(), nullable=False, comment='Update time'),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_uploaded', sa.Boolean(), nullable=False),
    sa.Column('path', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('extras', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_image_assets_create_time'), 'image_assets', ['create_time'], unique=False)
    op.create_index(op.f('ix_image_assets_update_time'), 'image_assets', ['update_time'], unique=False)
    op.create_table('users',
    sa.Column('create_time', sa.DateTime(), nullable=False, comment='Create time'),
    sa.Column('update_time', sa.DateTime(), nullable=False, comment='Update time'),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('username', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('hashed_password', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_create_time'), 'users', ['create_time'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_update_time'), 'users', ['update_time'], unique=False)
    op.create_table('embedding_configs',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('provider', sa.Enum('OPENAI', 'AZURE_OPENAI', 'OLLAMA', 'CUSTOM', name='embeddingprovider'), nullable=False),
    sa.Column('model_id', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('api_key', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('base_url', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('dimensions', sa.Integer(), nullable=True),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('create_time', sa.DateTime(), nullable=False, comment='Create time'),
    sa.Column('update_time', sa.DateTime(), nullable=False, comment='Update time'),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('extra_params', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_embedding_configs_create_time'), 'embedding_configs', ['create_time'], unique=False)
    op.create_index(op.f('ix_embedding_configs_update_time'), 'embedding_configs', ['update_time'], unique=False)
    op.create_index(op.f('ix_embedding_configs_user_id'), 'embedding_configs', ['user_id'], unique=False)
    op.create_table('llm_configs',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('provider', sa.Enum('OPENAI', 'OPENROUTER', 'ANTHROPIC', 'AZURE_OPENAI', 'OLLAMA', 'CUSTOM', name='llmprovider'), nullable=False),
    sa.Column('model_id', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('api_key', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('base_url', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('temperature', sa.Float(), nullable=False),
    sa.Column('max_tokens', sa.Integer(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('create_time', sa.DateTime(), nullable=False, comment='Create time'),
    sa.Column('update_time', sa.DateTime(), nullable=False, comment='Update time'),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('extra_params', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_llm_configs_create_time'), 'llm_configs', ['create_time'], unique=False)
    op.create_index(op.f('ix_llm_configs_update_time'), 'llm_configs', ['update_time'], unique=False)
    op.create_index(op.f('ix_llm_configs_user_id'), 'llm_configs', ['user_id'], unique=False)
    op.create_table('sessions',
    sa.Column('create_time', sa.DateTime(), nullable=False, comment='Create time'),
    sa.Column('update_time', sa.DateTime(), nullable=False, comment='Update time'),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'COMPLETED', 'FAILED', 'ARCHIVED', 'DELETED', name='sessionstatus'), nullable=False),
    sa.Column('topic', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('extra_data', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    comment='User sessions for PPT generation tasks'
    )
    op.create_index(op.f('ix_sessions_create_time'), 'sessions', ['create_time'], unique=False)
    op.create_index(op.f('ix_sessions_id'), 'sessions', ['id'], unique=False)
    op.create_index(op.f('ix_sessions_status'), 'sessions', ['status'], unique=False)
    op.create_index(op.f('ix_sessions_update_time'), 'sessions', ['update_time'], unique=False)
    op.create_index(op.f('ix_sessions_user_id'), 'sessions', ['user_id'], unique=False)
    op.create_table('task_ownership',
    sa.Column('create_time', sa.DateTime(), nullable=False, comment='Create time'),
    sa.Column('update_time', sa.DateTime(), nullable=False, comment='Update time'),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_task_ownership_create_time'), 'task_ownership', ['create_time'], unique=False)
    op.create_index(op.f('ix_task_ownership_task_id'), 'task_ownership', ['task_id'], unique=True)
    op.create_index(op.f('ix_task_ownership_update_time'), 'task_ownership', ['update_time'], unique=False)
    op.create_index(op.f('ix_task_ownership_user_id'), 'task_ownership', ['user_id'], unique=False)
    op.create_table('chat_messages',
    sa.Column('create_time', sa.DateTime(), nullable=False, comment='Create time'),
    sa.Column('update_time', sa.DateTime(), nullable=False, comment='Update time'),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.Enum('USER', 'ASSISTANT', 'SYSTEM', name='messagerole'), nullable=False),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('extra_data', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    comment='Chat conversation history for sessions'
    )
    op.create_index(op.f('ix_chat_messages_create_time'), 'chat_messages', ['create_time'], unique=False)
    op.create_index(op.f('ix_chat_messages_id'), 'chat_messages', ['id'], unique=False)
    op.create_index(op.f('ix_chat_messages_session_id'), 'chat_messages', ['session_id'], unique=False)
    op.create_index(op.f('ix_chat_messages_update_time'), 'chat_messages', ['update_time'], unique=False)
    op.create_index(op.f('ix_chat_messages_user_id'), 'chat_messages', ['user_id'], unique=False)
    op.create_table('file_metadata',
    sa.Column('create_time', sa.DateTime(), nullable=False, comment='Create time'),
    sa.Column('update_time', sa.DateTime(), nullable=False, comment='Update time'),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('filename', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('file_path', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=False),
    sa.Column('content_type', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('file_hash', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('parsed', sa.Boolean(), nullable=False),
    sa.Column('parse_error', sqlmodel.sql.sqltypes.AutoString(length=2000), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    comment='File metadata tracking for session-scoped files'
    )
    op.create_index(op.f('ix_file_metadata_create_time'), 'file_metadata', ['create_time'], unique=False)
    op.create_index(op.f('ix_file_metadata_file_hash'), 'file_metadata', ['file_hash'], unique=False)
    op.create_index(op.f('ix_file_metadata_id'), 'file_metadata', ['id'], unique=False)
    op.create_index(op.f('ix_file_metadata_session_id'), 'file_metadata', ['session_id'], unique=False)
    op.create_index(op.f('ix_file_metadata_update_time'), 'file_metadata', ['update_time'], unique=False)
    op.create_index(op.f('ix_file_metadata_user_id'), 'file_metadata', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_file_metadata_user_id'), table_name='file_metadata')
    op.drop_index(op.f('ix_file_metadata_update_time'), table_name='file_metadata')
    op.drop_index(op.f('ix_file_metadata_session_id'), table_name='file_metadata')
    op.drop_index(op.f('ix_file_metadata_id'), table_name='file_metadata')
    op.drop_index(op.f('ix_file_metadata_file_hash'), table_name='file_metadata')
    op.drop_index(op.f('ix_file_metadata_create_time'), table_name='file_metadata')
    op.drop_table('file_metadata')
    op.drop_index(op.f('ix_chat_messages_user_id'), table_name='chat_messages')
    op.drop_index(op.f('ix_chat_messages_update_time'), table_name='chat_messages')
    op.drop_index(op.f('ix_chat_messages_session_id'), table_name='chat_messages')
    op.drop_index(op.f('ix_chat_messages_id'), table_name='chat_messages')
    op.drop_index(op.f('ix_chat_messages_create_time'), table_name='chat_messages')
    op.drop_table('chat_messages')
    op.drop_index(op.f('ix_task_ownership_user_id'), table_name='task_ownership')
    op.drop_index(op.f('ix_task_ownership_update_time'), table_name='task_ownership')
    op.drop_index(op.f('ix_task_ownership_task_id'), table_name='task_ownership')
    op.drop_index(op.f('ix_task_ownership_create_time'), table_name='task_ownership')
    op.drop_table('task_ownership')
    op.drop_index(op.f('ix_sessions_user_id'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_update_time'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_status'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_id'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_create_time'), table_name='sessions')
    op.drop_table('sessions')
    op.drop_index(op.f('ix_llm_configs_user_id'), table_name='llm_configs')
    op.drop_index(op.f('ix_llm_configs_update_time'), table_name='llm_configs')
    op.drop_index(op.f('ix_llm_configs_create_time'), table_name='llm_configs')
    op.drop_table('llm_configs')
    op.drop_index(op.f('ix_embedding_configs_user_id'), table_name='embedding_configs')
    op.drop_index(op.f('ix_embedding_configs_update_time'), table_name='embedding_configs')
    op.drop_index(op.f('ix_embedding_configs_create_time'), table_name='embedding_configs')
    op.drop_table('embedding_configs')
    op.drop_index(op.f('ix_users_update_time'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_create_time'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_image_assets_update_time'), table_name='image_assets')
    op.drop_index(op.f('ix_image_assets_create_time'), table_name='image_assets')
    op.drop_table('image_assets')
    op.drop_index(op.f('ix_celery_tasksetmeta_update_time'), table_name='celery_tasksetmeta')
    op.drop_index(op.f('ix_celery_tasksetmeta_create_time'), table_name='celery_tasksetmeta')
    op.drop_table('celery_tasksetmeta')
    op.drop_index(op.f('ix_celery_taskmeta_update_time'), table_name='celery_taskmeta')
    op.drop_index(op.f('ix_celery_taskmeta_create_time'), table_name='celery_taskmeta')
    op.drop_table('celery_taskmeta')
    # ### end Alembic commands ###
